In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)
data

array([[-0.36716595,  0.10390228, -1.61881709],
       [ 0.02896913, -0.25743259, -1.06579479]])

In [29]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
arr[0,2]

3

In [28]:
arr2 = np.arange(10)
arr2[5:8] = 12
arr2

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [25]:
arr2

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [34]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0, 1]

array([4, 5, 6])